# Generated by Django 4.0.2 on 2022-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
