# Generated by Django 4.0.2 on 2022-04-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0002_registerdata_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
    ]
