# Generated by Django 4.0.2 on 2022-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0003_alter_registerdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10),
        ),
    ]
