# Generated by Django 4.0.2 on 2022-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0005_remove_registerdata_id_alter_registerdata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10),
        ),
    ]
