# Generated by Django 4.0.2 on 2022-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0006_alter_registerdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='userid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
