# Generated by Django 4.0.2 on 2022-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0007_alter_registerdata_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
