# Generated by Django 4.0.2 on 2022-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0009_alter_registerdata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='height',
            field=models.CharField(default=188, max_length=4),
        ),
        migrations.AddField(
            model_name='registerdata',
            name='weight',
            field=models.CharField(default=60, max_length=4),
        ),
    ]
