# Generated by Django 4.0.2 on 2022-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0010_registerdata_height_registerdata_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='height',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='weight',
            field=models.CharField(max_length=4),
        ),
    ]
