# Generated by Django 4.0.2 on 2022-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0012_alter_registerdata_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdata',
            name='height',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='weight',
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10),
        ),
    ]
