# Generated by Django 4.0.2 on 2022-04-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0014_registerdata_breakfast_registerdata_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdata',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='snacks',
        ),
    ]
