# Generated by Django 4.0.2 on 2022-04-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0015_remove_registerdata_breakfast_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registerdata',
            new_name='Register',
        ),
    ]
